modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="edenbound"
version="1.0.0"
displayName="Edenbound"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="albri, MCreator"

[[dependencies.edenbound]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



